#ifndef QTPHONENUMBERSTRING_GLOBAL_H
#define QTPHONENUMBERSTRING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPHONENUMBERSTRING_LIBRARY)
#  define QTPHONENUMBERSTRINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTPHONENUMBERSTRINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPHONENUMBERSTRING_GLOBAL_H
